
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operatorrole
rules:
- apiGroups:
  - mycontroller.tatacommunications.com
  resources:
  - testresources
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operatorrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator-role
subjects:
- kind: ServiceAccount
  name: my-serviceaccount
  namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myserviceaccount
  namespace: default