apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: TestResources.mycontroller.tatacommunications.com
spec:
  group: mycontroller.tatacommunications.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: TestResources
    singular: TestResource
    kind: TestResources
    shortNames:
    - ts