apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: testresources.mycontroller.tatacommunications.com
spec:
  group: mycontroller.tatacommunications.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: testresources
    singular: testresource
    kind: TestResource
    shortNames:
    - ts
