apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testresources.mycontroller.tatacommunications.com
spec:
  group: mycontroller.tatacommunications.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        #Schema is used for validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                firstNum:
                  default: 2
                  type: integer
                secondNum:
                  type: integer
                operation:
                  type: string
            status:
              type: object
              properties: 
                state:
                  type: string
                message:
                  type: string
                created_at:
                  type: string            
      #subresources for the custom resources
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: testresources
    singular: testresource
    kind: TestResource
    shortNames:
    - ts
