apiVersion: apps/v1
kind: Deployment
metadata:
 name: samplecontroller
 labels:
  app: samplecontroller
spec:
 replicas: 2
 selector:
  matchLabels:
   app: samplecontroller
 template:
  metadata:
   labels:
    app: samplecontroller
  spec:
   containers:
    - name: samplecontroller
      image: nextgen98/latestcontroller:v1
      ports:
       - containerPort: 80
